[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
remappings = [
    'forge-std=lib/forge-std/src/',
    'foundry-huff=lib/foundry-huff/src'
]

[rpc_endpoints]
flashbots = "https://rpc.flashbots.net/"

[fuzz]
runs = 4096

[fmt]
bracket_spacing = true
